# Generated by Django 2.2.12 on 2021-09-21 07:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(default='Java', max_length=100, unique=True)),
                ('organization', models.CharField(max_length=100)),
                ('course_start_datetime', models.DateTimeField(null=True)),
                ('course_end_datetime', models.DateTimeField(null=True)),
                ('course_des', models.CharField(max_length=200)),
                ('course_img', models.ImageField(null=True, upload_to='')),
                ('course_video', models.ImageField(null=True, upload_to='')),
                ('course_prerequisite', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enroll_start_datetime', models.DateTimeField(auto_now_add=True, null=True)),
                ('enroll_end_datetime', models.DateTimeField(null=True)),
                ('c_Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.Course')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
