# Generated by Django 3.2.7 on 2021-09-23 12:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_coursesec'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseSubSec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub', models.TextField(default='none', max_length=200)),
                ('courseSub', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='course.coursesec')),
            ],
        ),
    ]
