# Generated by Django 3.2.7 on 2021-09-23 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_coursesubsec'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursesubsec',
            name='sub',
            field=models.TextField(null=True),
        ),
    ]
