# Generated by Django 2.2.12 on 2021-09-27 06:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Studygroup_User', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_name', models.CharField(max_length=50, unique=True)),
                ('role_type', models.CharField(default=True, max_length=300)),
                ('role_des', models.CharField(default=True, max_length=300)),
                ('user_ID', models.ManyToManyField(blank=True, to='Studygroup_User.User')),
            ],
        ),
        migrations.CreateModel(
            name='Right',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_Id', models.ManyToManyField(to='Studygroup_SuperAdmin.Role')),
                ('user_ID', models.ManyToManyField(to='Studygroup_User.User')),
            ],
        ),
        migrations.CreateModel(
            name='BigBlueButton',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createLink', models.CharField(default=True, max_length=300)),
                ('meetingAdminUrl', models.CharField(default=True, max_length=300)),
                ('meetingUserUrl', models.CharField(default=True, max_length=300)),
                ('gpId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Studygroup_User.Group')),
            ],
        ),
    ]
