# Generated by Django 2.2.12 on 2021-09-27 06:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gpName', models.CharField(default='Java', max_length=100, unique=True)),
                ('date1', models.CharField(default='06/03/2021 18:00', max_length=100)),
                ('emailSend', models.CharField(default='No', max_length=10)),
                ('dateTime', models.DateTimeField(blank=True, null=True)),
                ('meet', models.CharField(max_length=300, null=True)),
                ('subscribe', models.CharField(default='okay', max_length=100)),
                ('role', models.CharField(default='user', max_length=100)),
                ('link', models.CharField(default='https://en.wikipedia.org/wiki/Main_Page', max_length=100)),
                ('description', models.CharField(default=' Enter some description', max_length=1000)),
                ('imagess', models.ImageField(default='images/group.png', upload_to='images/')),
                ('topic', models.CharField(default='topic', max_length=100)),
                ('createdBy', models.DateTimeField(auto_now_add=True)),
                ('imgs', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, unique=True)),
                ('full_name', models.CharField(max_length=200)),
                ('avatar', models.ImageField(blank=True, default='images/user.png', null=True, upload_to='images/')),
                ('approve', models.CharField(default='No', max_length=200)),
                ('email', models.CharField(max_length=100, unique=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('password', models.CharField(max_length=20)),
                ('imgs', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(default='manager', max_length=100)),
                ('group', models.CharField(default='Java', max_length=100)),
                ('messages', models.TextField(blank=True, max_length=100, null=True)),
                ('images', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('files', models.FileField(blank=True, null=True, upload_to='files/')),
                ('img', models.TextField(null=True)),
                ('createdBy', models.DateTimeField(auto_now_add=True)),
                ('grp_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Studygroup_User.Group')),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(default='abc', max_length=200)),
                ('role', models.CharField(default='user', max_length=100)),
                ('gpName', models.CharField(default='Java', max_length=100)),
                ('photo', models.ImageField(blank=True, default='images/group.png', null=True, upload_to='images/')),
                ('userURL', models.CharField(default='user', max_length=300)),
                ('adminURL', models.CharField(default='admin', max_length=300)),
                ('createdBy', models.DateTimeField(auto_now_add=True)),
                ('grp_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Studygroup_User.Group')),
                ('user_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Studygroup_User.User')),
            ],
        ),
        migrations.AddField(
            model_name='group',
            name='userId',
            field=models.ManyToManyField(to='Studygroup_User.User'),
        ),
        migrations.CreateModel(
            name='CreateRole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_name', models.CharField(max_length=100, unique=True)),
                ('role_type', models.CharField(default=True, max_length=300)),
                ('role_des', models.CharField(default=True, max_length=300)),
                ('user_ID', models.ManyToManyField(blank=True, to='Studygroup_User.User')),
            ],
        ),
    ]
